### PR TITLE
Code and live view

### PR DESCRIPTION
**Pull request by Charvine-300**
## Description

This PR adds one component for creating a checklist to track user progress

## Acceptance Criteria

- [x] Created the `Code.js` component in building the checklist in a component folder in the `src` directory.
- [x]  Heading: Code and Live View
- [x]   Input fields must be editable
- [x]  Input fields are accessible
- [x]  The new component is imported and displayed in the `App.js` component
- [x]  Only the new component is displayed

## Additional AC

- [x] Saved data to localStorage

## Screenshots
Web capture_20-10-2022_15553_localhost

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✅  | :sparkles: New feature     |

## Testing Steps / QA Criteria

Use the input bar at the top to add new items to your checklist

### CODE REVIEW

**Comment by YuriDevAT** [comment]
Thank you for your contribution, your code is amazing. 🎆 

Unfortunately, my instructions weren't clear enough and I am really sorry for that. 😞 

The checklist list should look like the one I [linked in the issue](https://github.com/YuriDevAT/job-seekers/wiki/Checklist-for-your-portfolio-projects) and the [screenshot](https://github.com/YurisCodingClub/pro-check/issues/4) I added to the issue. The items are hard coded text. No` <input type="text">` needed, **only** `<input type="checkbox">`. No `"Add New Task" Button` needed (which I also do not find in the AC). It is a finished list already, where users can check if they did what's in the list.

If you have any other question, please do not hesitate to ask.

**Comment by Charvine-300** [comment]
>Thank you @YuriDevAT for the review and clarification of the task. I will make the changes and get back to you on it 😊✨

**Comment by Charvine-300** [comment]
## Description 

I removed dynamic development in the `Code.js` component and hardcoded the checklist

## Related Issue

Closes #4 


## Screenshots
Web capture_21-10-2022_23102_localhost


##  Acceptance Criteria
- [x]  Create a component called `Code.js` and save it in a folder called components in the `src` directory
- [x]  Heading: Code and Live View
- [x]  Input fields must be editable
- [x]  Input fields are [accessible](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form)
- [ ]   No stylings, just plain HTML
- [x]  Added small styling to make output clean
- [x]  The new component is imported and displayed in the `App.js` component
- [x]  Only the new component is displayed


## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✅  | :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |


## Additional Information
 
I would like to add the localStorage feature to the checklist. Please provide me with clarification on what exactly to save to localStorage and what events should occur for that to be triggered

**Comment by YuriDevAT** [comment]
For the `localStorage` feature: Just the information that it is checked. When the user refreshes the browser, all the checked items should still be checked.

**Comment by Charvine-300** [comment]
Alright then. I will implement that feature back into the application and notify you when it is complete✨

**Comment by Charvine-300** [comment]
## Description

Implemented localStorage to save the progress of the checklist 


## Screenshots
Web capture_26-10-2022_0356_localhost


## Additional AC

- [x]  Save data in localStorage


## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  [x]  | :bug: Bug fix              |
| [x]   | :sparkles: New feature     |

**Comment by Charvine-300** [comment]
Hey @YuriDevAT I have implemented the localStorage feature to the checklist. It took a lot of tries 😅 but it's done ✨

**Comment by YuriDevAT** [comment]
Thanks @Charvine-300 👍🏽. It seems when refreshing the page, the checked state is being stored even if I uncheck a box again - like, in case I would accidentally check a box, the checked state keeps being stored after a refresh.

**Comment by Charvine-300** [comment]
> Thanks @Charvine-300 👍🏽. It seems when refreshing the page, the checked state is being stored even if I uncheck a box again - like, in case I would accidentally check a box, the checked state keeps being stored after a refresh.

@YuriDevAT I will look into this and handle it. Thanks ✨

**Comment by Charvine-300** [comment]
Hey, @YuriDevAT I have worked on the issue and would like you to take a look at it, and see if it's still giving that issue on your end or any other issue. Thank you ✨

**Comment by YuriDevAT** [comment]
Seems good now 👍🏽 great work, @Charvine-300, thanks for you contribution  🥳

**Pull request merged**
